version: '2'

services:
# apigw service
  apigw:
    image: bigtony.fileserver.com/filestore/apigw
    networks:
      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=apigw"
      - "traefik.frontend.rule=Host:apigw.fileserver.com"
      - "traefik.docker.port=8080"
# upload service
  upload:
    image: bigtony.fileserver.com/filestore/upload
    networks:
      - web
    volumes:
      - /Users/bigtony/tmp/fileserver:/data/fileserver
      - /Users/bigtony/tmp/fileserver_part:/data/fileserver_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=upload"
      - "traefik.frontend.rule=Host:upload.fileserver.com"
      - "traefik.docker.port=28080"
# download service
  download:
    image: bigtony.fileserver.com/filestore/download
    networks:
      - web
    volumes:
      - /Users/bigtony/tmp/fileserver:/data/fileserver
      - /Users/bigtony/tmp/fileserver_part:/data/fileserver_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=download"
      - "traefik.frontend.rule=Host:download.fileserver.com"
      - "traefik.docker.port=38080"
# account service
  account:
    image: bigtony.fileserver.com/filestore/account
    networks:
      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
# transfer service
  transfer:
    image: bigtony.fileserver.com/filestore/transfer
    networks:
      - web
    volumes:
      - /Users/bigtony/tmp/fileserver:/data/fileserver
      - /Users/bigtony/tmp/fileserver_part:/data/fileserver_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
# dbproxy service
  dbproxy:
    image: bigtony.fileserver.com/filestore/dbproxy
    networks:
      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
networks:
  web:
    external: false
#      name: fileserver